from lexishift_core.replacement.core import (
    Match,
    MeaningRule,
    Normalizer,
    PhraseTrie,
    PhraseTrieNode,
    Replacer,
    ReplacementResult,
    RuleMetadata,
    SynonymNormalizer,
    Token,
    Tokenizer,
    VocabPool,
    VocabRule,
)
from lexishift_core.replacement.builder import BuildOptions, build_vocab_pool, expand_vocab_rules
from lexishift_core.replacement.inflect import (
    DEFAULT_FORMS,
    FORM_GERUND,
    FORM_PAST,
    FORM_PLURAL,
    FORM_POSSESSIVE,
    FORM_THIRD_PERSON,
    InflectionGenerator,
    InflectionOverrides,
    InflectionSpec,
    expand_phrase,
)
from lexishift_core.replacement.pipeline import (
    ReplacementMode,
    ReplacementPipeline,
    build_meaning_pool,
    compile_pipeline,
)
from lexishift_core.persistence.import_export import (
    export_app_settings_json,
    export_app_settings_code,
    export_app_settings_python,
    export_dataset_json,
    export_dataset_code,
    export_dataset_python,
    import_app_settings_json,
    import_app_settings_code,
    import_app_settings_python,
    import_dataset_json,
    import_dataset_code,
    import_dataset_python,
)
from lexishift_core.persistence.settings import (
    AppSettings,
    ImportExportSettings,
    Profile,
    SynonymSourceSettings,
    load_app_settings,
    save_app_settings,
    settings_from_dict,
    settings_to_dict,
)
from lexishift_core.srs.selector import (
    ScoredCandidate,
    ScoreBreakdown,
    SelectorCandidate,
    SelectorConfig,
    SelectorPenalties,
    SelectorWeights,
    filter_candidates,
    rank_candidates,
    score_candidate,
)
from lexishift_core.srs.growth import (
    SrsGrowthConfig,
    SrsGrowthPlan,
    apply_growth_plan,
    grow_srs_store,
    normalize_coverage_scalar,
    plan_srs_growth,
    resolve_allowed_pairs,
)
from lexishift_core.srs.set_strategy import (
    OBJECTIVE_BOOTSTRAP,
    OBJECTIVE_GROWTH,
    OBJECTIVE_REFRESH,
    STRATEGY_ADAPTIVE_REFRESH,
    STRATEGY_FREQUENCY_BOOTSTRAP,
    STRATEGY_PROFILE_BOOTSTRAP,
    STRATEGY_PROFILE_GROWTH,
    normalize_set_objective,
    normalize_set_strategy,
)
from lexishift_core.srs.set_planner import (
    SrsSetPlan,
    SrsSetPlanRequest,
    build_srs_set_plan,
    plan_to_dict,
)
from lexishift_core.srs.signal_queue import (
    SIGNAL_EXPOSURE,
    SIGNAL_FEEDBACK,
    SrsSignalEvent,
    append_signal_event,
    load_signal_events,
    save_signal_events,
    summarize_signal_events,
)
from lexishift_core.srs.store_ops import (
    append_history,
    build_item_id,
    find_item,
    record_exposure,
    record_feedback,
    upsert_item,
)
from lexishift_core.srs.time import format_ts, now_utc, parse_ts
from lexishift_core.resources.synonyms import SynonymGenerator, SynonymOptions, SynonymSources
from lexishift_core.resources.dict_loaders import (
    load_jmdict_glosses,
    load_jmdict_glosses_ordered,
    load_jmdict_lemmas,
)
from lexishift_core.frequency import (
    FrequencyLexicon,
    FrequencySourceConfig,
    build_frequency_provider,
    load_frequency_lexicon,
)
from lexishift_core.rulegen.generation import (
    MappingCandidateSource,
    RuleCandidate,
    RuleConfidenceSignals,
    RuleGenerationConfig,
    RuleGenerationPipeline,
    RuleGenerationResult,
    RuleScorer,
    RuleScoreWeights,
    SimpleSignalProvider,
)
from lexishift_core.rulegen.utils import (
    BasicStringNormalizer,
    InflectionVariantExpander,
    NonEmptyFilter,
    SingleWordFilter,
)
from lexishift_core.persistence.storage import (
    InflectionSettings,
    LearningSettings,
    VocabSettings,
    VocabDataset,
    build_options_from_settings,
    build_vocab_pool_from_dataset,
    dataset_from_dict,
    dataset_to_dict,
    load_vocab_dataset,
    load_vocab_pool,
    save_vocab_dataset,
    save_vocab_pool,
)

_LAZY_EXPORT_MODULES = {
    "SqliteFrequencyProvider": "lexishift_core.frequency.providers",
    "SqliteFrequencyProviderConfig": "lexishift_core.frequency.providers",
    "build_sqlite_frequency_provider": "lexishift_core.frequency.providers",
    "SqliteFrequencyConfig": "lexishift_core.frequency.sqlite_store",
    "SqliteFrequencyStore": "lexishift_core.frequency.sqlite_store",
    "EnJaRulegenConfig": "lexishift_core.rulegen.pairs.en_ja",
    "build_en_ja_pipeline": "lexishift_core.rulegen.pairs.en_ja",
    "generate_en_ja_results": "lexishift_core.rulegen.pairs.en_ja",
    "generate_en_ja_rules": "lexishift_core.rulegen.pairs.en_ja",
    "SeedSelectionConfig": "lexishift_core.srs.seed",
    "SeedWord": "lexishift_core.srs.seed",
    "build_seed_candidates": "lexishift_core.srs.seed",
    "seed_to_selector_candidates": "lexishift_core.srs.seed",
    "GlossDecay": "lexishift_core.scoring.weighting",
    "PmwWeighting": "lexishift_core.scoring.weighting",
    "RankWeighting": "lexishift_core.scoring.weighting",
    "PracticeGateState": "lexishift_core.srs",
    "SrsHistoryEntry": "lexishift_core.srs",
    "SrsItem": "lexishift_core.srs",
    "SrsPairSettings": "lexishift_core.srs",
    "SrsSettings": "lexishift_core.srs",
    "SrsStore": "lexishift_core.srs",
    "SrsSync": "lexishift_core.srs",
    "load_srs_settings": "lexishift_core.srs",
    "load_srs_store": "lexishift_core.srs",
    "save_srs_settings": "lexishift_core.srs",
    "save_srs_store": "lexishift_core.srs",
    "srs_bundle_from_dict": "lexishift_core.srs",
    "srs_bundle_to_dict": "lexishift_core.srs",
    "srs_settings_from_dict": "lexishift_core.srs",
    "srs_settings_to_dict": "lexishift_core.srs",
    "srs_store_from_dict": "lexishift_core.srs",
    "srs_store_to_dict": "lexishift_core.srs",
    "RATING_AGAIN": "lexishift_core.srs.scheduler",
    "RATING_EASY": "lexishift_core.srs.scheduler",
    "RATING_GOOD": "lexishift_core.srs.scheduler",
    "RATING_HARD": "lexishift_core.srs.scheduler",
    "apply_feedback": "lexishift_core.srs.scheduler",
    "select_active_items": "lexishift_core.srs.scheduler",
    "PracticeGate": "lexishift_core.srs.gate",
    "select_rules_for_practice": "lexishift_core.srs.gate",
}

__all__ = [
    "Match",
    "MeaningRule",
    "Normalizer",
    "PhraseTrie",
    "PhraseTrieNode",
    "Replacer",
    "ReplacementResult",
    "ReplacementMode",
    "ReplacementPipeline",
    "RuleMetadata",
    "SynonymNormalizer",
    "Token",
    "Tokenizer",
    "InflectionSettings",
    "LearningSettings",
    "VocabSettings",
    "VocabDataset",
    "VocabPool",
    "VocabRule",
    "build_meaning_pool",
    "compile_pipeline",
    "build_options_from_settings",
    "build_vocab_pool_from_dataset",
    "build_vocab_pool",
    "expand_vocab_rules",
    "BuildOptions",
    "DEFAULT_FORMS",
    "FORM_GERUND",
    "FORM_PAST",
    "FORM_PLURAL",
    "FORM_POSSESSIVE",
    "FORM_THIRD_PERSON",
    "InflectionGenerator",
    "InflectionOverrides",
    "InflectionSpec",
    "expand_phrase",
    "dataset_from_dict",
    "dataset_to_dict",
    "load_vocab_dataset",
    "load_vocab_pool",
    "save_vocab_dataset",
    "save_vocab_pool",
    "export_dataset_json",
    "export_dataset_code",
    "export_dataset_python",
    "import_dataset_json",
    "import_dataset_code",
    "import_dataset_python",
    "export_app_settings_json",
    "export_app_settings_code",
    "export_app_settings_python",
    "import_app_settings_json",
    "import_app_settings_code",
    "import_app_settings_python",
    "AppSettings",
    "ImportExportSettings",
    "Profile",
    "SynonymSourceSettings",
    "load_app_settings",
    "save_app_settings",
    "settings_from_dict",
    "settings_to_dict",
    "SynonymGenerator",
    "SynonymOptions",
    "SynonymSources",
    "load_jmdict_glosses",
    "load_jmdict_glosses_ordered",
    "load_jmdict_lemmas",
    "FrequencyLexicon",
    "FrequencySourceConfig",
    "build_frequency_provider",
    "load_frequency_lexicon",
    "SqliteFrequencyConfig",
    "SqliteFrequencyStore",
    "SqliteFrequencyProvider",
    "SqliteFrequencyProviderConfig",
    "build_sqlite_frequency_provider",
    "MappingCandidateSource",
    "RuleCandidate",
    "RuleConfidenceSignals",
    "RuleGenerationConfig",
    "RuleGenerationPipeline",
    "RuleGenerationResult",
    "RuleScorer",
    "RuleScoreWeights",
    "SimpleSignalProvider",
    "BasicStringNormalizer",
    "InflectionVariantExpander",
    "NonEmptyFilter",
    "SingleWordFilter",
    "EnJaRulegenConfig",
    "build_en_ja_pipeline",
    "generate_en_ja_results",
    "generate_en_ja_rules",
    "SeedSelectionConfig",
    "SeedWord",
    "build_seed_candidates",
    "seed_to_selector_candidates",
    "GlossDecay",
    "PmwWeighting",
    "RankWeighting",
    "PracticeGateState",
    "SrsHistoryEntry",
    "SrsItem",
    "SrsPairSettings",
    "SrsSettings",
    "SrsStore",
    "SrsSync",
    "load_srs_settings",
    "load_srs_store",
    "save_srs_settings",
    "save_srs_store",
    "srs_bundle_from_dict",
    "srs_bundle_to_dict",
    "srs_settings_from_dict",
    "srs_settings_to_dict",
    "srs_store_from_dict",
    "srs_store_to_dict",
    "RATING_AGAIN",
    "RATING_EASY",
    "RATING_GOOD",
    "RATING_HARD",
    "apply_feedback",
    "select_active_items",
    "PracticeGate",
    "select_rules_for_practice",
    "SelectorWeights",
    "SelectorPenalties",
    "SelectorConfig",
    "SelectorCandidate",
    "ScoreBreakdown",
    "ScoredCandidate",
    "filter_candidates",
    "score_candidate",
    "rank_candidates",
    "SrsGrowthConfig",
    "SrsGrowthPlan",
    "apply_growth_plan",
    "grow_srs_store",
    "normalize_coverage_scalar",
    "plan_srs_growth",
    "resolve_allowed_pairs",
    "OBJECTIVE_BOOTSTRAP",
    "OBJECTIVE_GROWTH",
    "OBJECTIVE_REFRESH",
    "STRATEGY_ADAPTIVE_REFRESH",
    "STRATEGY_FREQUENCY_BOOTSTRAP",
    "STRATEGY_PROFILE_BOOTSTRAP",
    "STRATEGY_PROFILE_GROWTH",
    "normalize_set_objective",
    "normalize_set_strategy",
    "SrsSetPlan",
    "SrsSetPlanRequest",
    "build_srs_set_plan",
    "plan_to_dict",
    "SIGNAL_EXPOSURE",
    "SIGNAL_FEEDBACK",
    "SrsSignalEvent",
    "append_signal_event",
    "load_signal_events",
    "save_signal_events",
    "summarize_signal_events",
    "append_history",
    "build_item_id",
    "find_item",
    "record_exposure",
    "record_feedback",
    "upsert_item",
    "format_ts",
    "now_utc",
    "parse_ts",
]


def __getattr__(name: str):
    module_name = _LAZY_EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = __import__(module_name, fromlist=[name])
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
