(() => {
  const root = (globalThis.LexiShift = globalThis.LexiShift || {});
  root.optionsUiManagerDomIds = Object.freeze(
    [
  "options-main-content",
  "enabled", "highlight-enabled", "highlight-color", "highlight-color-text",
  "max-one-per-block", "allow-adjacent", "max-replacements-per-page",
  "max-replacements-per-sentence", "max-replacements-per-lemma-page",
  "debug-enabled", "debug-focus-word",
  "srs-enabled", "source-language", "target-language", "srs-max-active",
  "target-language-gear", "target-language-prefs-modal-backdrop",
  "target-language-prefs-modal", "target-language-prefs-modal-ok", "target-language-modules-list",
  "srs-profile-id", "srs-profile-refresh", "srs-profile-status",
  "profile-bg-backdrop-color",
  "profile-bg-opacity", "profile-bg-opacity-value",
  "profile-bg-file", "profile-bg-remove",
  "profile-bg-status", "profile-bg-preview-wrap", "profile-bg-preview",
  "profile-bg-focal-marker", "profile-bg-position-reset",
  "profile-card-theme-hue", "profile-card-theme-hue-value",
  "profile-card-theme-saturation", "profile-card-theme-saturation-value",
  "profile-card-theme-brightness", "profile-card-theme-brightness-value",
  "profile-card-theme-transparency", "profile-card-theme-transparency-value",
  "profile-card-theme-reset",
  "srs-bootstrap-top-n", "srs-initial-active-count",
  "srs-topic-interests", "srs-proficiency-estimate", "srs-challenge-target",
  "srs-proficiency-estimate-value", "srs-proficiency-estimate-saved", "srs-proficiency-estimate-restore",
  "srs-save-preferences", "srs-preferences-save-status",
  "srs-sound-enabled", "srs-highlight-color", "srs-highlight-color-text",
  "srs-semantic-admission-status", "srs-semantic-admission-status-detail",
  "srs-auto-refresh-min-feedback",
  "srs-auto-refresh-min-good-easy", "srs-auto-refresh-repeat-min-good-easy",
  "srs-auto-refresh-cooldown",
  "srs-exposure-logging-enabled",
  "srs-browsing-admission-signals-enabled",
  "srs-admission-preview", "srs-admission-preview-output",
  "srs-initialize-set", "srs-rebalance-preview", "srs-rebalance-apply",
  "srs-story-sampling-curtain",
  "srs-refresh-set", "srs-runtime-diagnostics",
  "srs-rulegen-sampled-preview",
  "srs-story-pair-list",
  "srs-story-current-card", "srs-story-current-pair", "srs-story-current-meta",
  "srs-rulegen-output", "srs-delete-story", "helper-status",
  "srs-story-start", "srs-story-flow-backdrop", "srs-story-flow",
  "srs-story-flow-close", "srs-story-flow-source-language",
  "srs-story-flow-target-language", "srs-story-flow-profile-id",
  "srs-story-flow-proficiency-estimate", "srs-story-flow-topic-interests",
  "srs-story-flow-proficiency-estimate-value",
  "srs-story-flow-max-active", "srs-story-flow-initial-active-count", "srs-story-flow-sample",
  "srs-story-flow-initialize", "srs-story-flow-preview-output",
  "srs-story-flow-busy-backdrop", "srs-story-flow-busy-message",
  "srs-story-flow-resource-check", "srs-story-flow-resource-message", "srs-story-flow-resource-list", "srs-story-flow-open-resource-settings", "srs-story-flow-retry-resources",
  "helper-last-sync", "debug-helper-test",
  "debug-semantic-pack-inventory-path", "debug-semantic-pack-id",
  "debug-semantic-pack-default-data-root", "debug-semantic-pack-data-root",
  "debug-semantic-pack-install", "debug-semantic-pack-install-output",
  "debug-helper-test-output", "debug-open-data-dir",
  "debug-open-data-dir-output", "ui-language", "rules", "save",
  "status", "rules-file", "import-file", "export-file", "file-status",
  "custom-ruleset-enabled",
  "profile-rulesets-list", "profile-rulesets-status", "profile-rulesets-refresh",
  "share-center-open-export", "share-center-open-import",
  "share-center-export-backdrop", "share-center-export-modal", "share-center-export-close",
  "share-center-import-backdrop", "share-center-import-modal", "share-center-import-close",
  "share-center-export-mode-full", "share-center-export-mode-custom", "share-center-tree-panel",
  "share-center-parent-profile", "share-center-parent-rulesets", "share-center-parent-srs",
  "share-center-parent-appearance", "share-center-parent-module-histories",
  "share-center-srs-pair-items", "share-center-srs-pair-status",
  "share-center-target-profile-settings",
  "share-center-target-appearance-theme",
  "share-center-ruleset-items", "share-center-ruleset-status",
  "share-center-module-items", "share-center-module-status",
  "share-center-summary-target", "share-center-summary-groups",
  "share-center-summary-output",
  "share-center-generate", "share-center-export-status",
  "share-center-import-file", "share-center-import-file-name", "share-center-import", "share-center-import-status",
  "share-center-status",
  "rules-updated", "rules-count", "share-code", "share-code-scope", "share-code-cjk",
  "generate-code", "import-code", "copy-code", "open-desktop-app",
  "open-bd-plugin"
]);
})();
