from __future__ import annotations

from lexishift_core.frequency.sqlite import ParseConfig
from lexishift_core.pos.ud_ancora import (
    DEFAULT_PACK_ID as DEFAULT_UD_ANCORA_PACK_ID,
    DEFAULT_PROVIDER as DEFAULT_UD_ANCORA_PROVIDER,
    DEFAULT_SOURCE_NAME as DEFAULT_UD_ANCORA_SOURCE_NAME,
    DEFAULT_SOURCE_URL as DEFAULT_UD_ANCORA_SOURCE_URL,
    DEFAULT_UD_ANCORA_URLS,
)
from language_packs_catalog_models import (
    AUTO_DOWNLOAD_MODE,
    CC_BY_4_URL,
    CC_BY_SA_3_URL,
    CC_BY_SA_4_URL,
    EXPECTED_NOT_VERIFIED,
    GPL_2_URL,
    LGPL_2_1_URL,
    MANUAL_SUPPLY_MODE,
    VERIFIED_FROM_UPSTREAM,
    FrequencyPackInfo,
    LanguagePackInfo,
    PosOverlayPackInfo,
    SemanticPackInfo,
)

LANGUAGE_PACKS = [
    LanguagePackInfo(
        pack_id="wordnet-en",
        name="WordNet",
        language="English",
        source="Princeton",
        size="72.5 MB",
        url="https://en-word.net/static/english-wordnet-2025-json.zip",
        wayback_url="https://web.archive.org/web/*/https://en-word.net/static/english-wordnet-2025-json.zip",
        filename="english-wordnet-2025-json.zip",
        local_kind="dir",
        name_key="packs.wordnet",
        language_key="languages.english",
        source_key="providers.princeton",
        license_name="CC BY 4.0",
        license_url=CC_BY_4_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="moby-en",
        name="Moby Thesaurus",
        language="English",
        source="Moby",
        size="24.9 MB",
        url="https://dn790001.ca.archive.org/0/items/mobythesauruslis03202gut/mthesaur.txt",
        wayback_url="https://web.archive.org/web/*/https://dn790001.ca.archive.org/0/items/mobythesauruslis03202gut/mthesaur.txt",
        filename="mthesaur.txt",
        local_kind="file",
        name_key="packs.moby",
        language_key="languages.english",
        source_key="providers.moby",
        license_name="Project Gutenberg public-domain notice",
        license_url="https://www.gutenberg.org/ebooks/3202",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="openthesaurus-de",
        name="OpenThesaurus",
        language="German",
        source="OpenThesaurus",
        size="2.6 MB",
        url="https://gitlab.htl-perg.ac.at/20180016/hue_junit/-/raw/master/Thesaurus/src/openthesaurus.txt?inline=false",
        wayback_url="https://web.archive.org/web/*/https://gitlab.htl-perg.ac.at/20180016/hue_junit/-/raw/master/Thesaurus/src/openthesaurus.txt?inline=false",
        filename="openthesaurus.txt",
        local_kind="file",
        name_key="packs.openthesaurus",
        language_key="languages.german",
        source_key="providers.openthesaurus",
        license_name="LGPL 2.1 or later",
        license_url=LGPL_2_1_URL,
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="odenet-de",
        name="OdeNet",
        language="German",
        source="OdeNet",
        size="15 MB",
        url="https://raw.githubusercontent.com/hdaSprachtechnologie/odenet/refs/heads/master/odenet_oneline.xml",
        wayback_url="https://web.archive.org/web/20251101/https://raw.githubusercontent.com/hdaSprachtechnologie/odenet/refs/heads/master/odenet_oneline.xml",
        filename="odenet_oneline.xml",
        local_kind="file",
        name_key="packs.odenet",
        language_key="languages.german",
        source_key="providers.odenet",
        license_name="CC BY-SA 4.0",
        license_url=CC_BY_SA_4_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="jp-wordnet-sqlite",
        name="Japanese WordNet (SQLite)",
        language="Japanese",
        source="NTT",
        size="194 MB",
        url="https://github.com/bond-lab/wnja/releases/download/v1.1/wnjpn.db.gz",
        wayback_url="https://web.archive.org/web/*/https://github.com/bond-lab/wnja/releases/download/v1.1/wnjpn.db.gz",
        filename="wnjpn.db.gz",
        local_kind="file",
        name_key="packs.jp_wordnet_sqlite",
        language_key="languages.japanese",
        source_key="providers.ntt",
        license_name="Japanese WordNet license",
        license_url="https://bond-lab.github.io/wnja/license.txt",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="jp-wordnet",
        name="Japanese WordNet",
        language="Japanese",
        source="NTT",
        size="29.2 MB",
        url="https://github.com/bond-lab/wnja/releases/download/v1.1/wnjpn-all.tab.gz",
        wayback_url="https://web.archive.org/web/*/https://github.com/bond-lab/wnja/releases/download/v1.1/wnjpn-all.tab.gz",
        filename="wnjpn-all.tab.gz",
        local_kind="file",
        name_key="packs.jp_wordnet",
        language_key="languages.japanese",
        source_key="providers.ntt",
        license_name="Japanese WordNet license",
        license_url="https://bond-lab.github.io/wnja/license.txt",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="jmdict-ja-en",
        name="JMDict",
        language="Japanese → English",
        source="EDRDG",
        size="61.6 MB",
        url="https://www.edrdg.org/pub/Nihongo/JMdict_e.gz",
        wayback_url="https://web.archive.org/web/20250101/https://www.edrdg.org/pub/Nihongo/JMdict_e.gz",
        filename="JMdict_e.gz",
        local_kind="file",
        name_key="packs.jmdict",
        language_key="languages.japanese_english",
        source_key="providers.edrdg",
        license_name="CC BY-SA 4.0",
        license_url="https://www.edrdg.org/edrdg/licence.html",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="kanjidic2-ja",
        name="KANJIDIC2",
        language="Japanese kanji",
        source="EDRDG",
        size="1.5 MB",
        url="https://www.edrdg.org/kanjidic/kanjidic2.xml.gz",
        wayback_url="https://web.archive.org/web/*/https://www.edrdg.org/kanjidic/kanjidic2.xml.gz",
        filename="kanjidic2.xml.gz",
        local_kind="dir",
        required_files=("kanjidic2.xml",),
        license_name="CC BY-SA 4.0",
        license_url="https://www.edrdg.org/edrdg/licence.html",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
        license_notes=(
            "Kanji grade, stroke count, old JLPT kanji level, and kanji frequency source.",
            "Used as optional en-ja learner-difficulty signal enrichment.",
        ),
    ),
    LanguagePackInfo(
        pack_id="jmnedict-ja",
        name="JMnedict",
        language="Japanese names",
        source="EDRDG",
        size="11.9 MB",
        url="https://www.edrdg.org/pub/Nihongo/JMnedict.xml.gz",
        wayback_url="https://web.archive.org/web/*/https://www.edrdg.org/pub/Nihongo/JMnedict.xml.gz",
        filename="JMnedict.xml.gz",
        local_kind="dir",
        required_files=("JMnedict.xml",),
        license_name="CC BY-SA 4.0",
        license_url="https://www.edrdg.org/edrdg/licence.html",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
        license_notes=(
            "Japanese proper-name dictionary used as optional en-ja name/admission signal enrichment.",
        ),
    ),
    LanguagePackInfo(
        pack_id="kanjivg-ja",
        name="KanjiVG",
        language="Japanese kanji graphics",
        source="KanjiVG",
        size="3.4 MB",
        url="https://github.com/KanjiVG/kanjivg/releases/download/r20250816/kanjivg-20250816.xml.gz",
        wayback_url=(
            "https://web.archive.org/web/*/https://github.com/KanjiVG/kanjivg/"
            "releases/download/r20250816/kanjivg-20250816.xml.gz"
        ),
        filename="kanjivg-20250816.xml.gz",
        local_kind="dir",
        required_files=("kanjivg-20250816.xml",),
        source_version="kanjivg:r20250816",
        download_size_bytes=3_608_178,
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
        license_notes=(
            "Kanji stroke path and component structure used as optional en-ja visual-complexity signal enrichment.",
        ),
    ),
    LanguagePackInfo(
        pack_id="jlpt-tanos-vocab-ja",
        name="Tanos JLPT Vocabulary",
        language="Japanese learner vocabulary",
        source="Jonathan Waller / Tanos, structured by Bluskyo",
        size="191.6 KB",
        url=(
            "https://raw.githubusercontent.com/Bluskyo/JLPT_Vocabulary/main/"
            "data/vocab/results/JLPT_vocab_ALL.csv"
        ),
        wayback_url=(
            "https://web.archive.org/web/*/https://raw.githubusercontent.com/"
            "Bluskyo/JLPT_Vocabulary/main/data/vocab/results/JLPT_vocab_ALL.csv"
        ),
        filename="JLPT_vocab_ALL.csv",
        local_kind="file",
        download_size_bytes=196_190,
        name_key="packs.jlpt_tanos_vocab",
        language_key="languages.japanese_learner_vocabulary",
        source_key="providers.tanos_bluskyo",
        license_name="Creative Commons Attribution",
        license_url="https://www.tanos.co.uk/jlpt/sharing/",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
        license_notes=(
            "JLPT vocabulary level list from Jonathan Waller/Tanos under Tanos sharing terms.",
            "Machine-readable CSV is the Bluskyo structured conversion of the Tanos vocabulary list.",
            "Used as optional en-ja learner-difficulty signal enrichment.",
        ),
    ),
    LanguagePackInfo(
        pack_id="sbsjapanese1-ja",
        name="Step-by-Step Japanese 1",
        language="Japanese beginner lesson vocabulary",
        source="Mimi Yu / UT San Antonio Pressbooks",
        size="15.8 MB",
        url="https://utsa.pressbooks.pub/sbsjapanese1/open/download?type=epub",
        wayback_url="https://web.archive.org/web/*/https://utsa.pressbooks.pub/sbsjapanese1/",
        filename="sbsjapanese1.zip",
        local_kind="dir",
        name_key="packs.sbsjapanese1",
        language_key="languages.japanese_beginner_vocabulary",
        source_key="providers.utsa_pressbooks",
        license_name="CC BY 4.0",
        license_url="https://creativecommons.org/licenses/by/4.0/",
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
        license_notes=(
            "Pressbooks export is saved as .zip so LexiShift can extract the EPUB archive.",
            "Lesson-order vocabulary source for optional en-ja beginner-difficulty enrichment.",
            "Book is CC BY 4.0 except where otherwise noted.",
        ),
    ),
    LanguagePackInfo(
        pack_id="freedict-de-en",
        name="FreeDict (DE→EN)",
        language="German → English",
        source="FreeDict",
        size="449.6 MB",
        url="https://download.freedict.org/dictionaries/deu-eng/1.9-fd1/freedict-deu-eng-1.9-fd1.src.tar.xz",
        wayback_url="https://web.archive.org/web/*/https://download.freedict.org/dictionaries/deu-eng/1.9-fd1/freedict-deu-eng-1.9-fd1.src.tar.xz",
        filename="freedict-deu-eng-1.9-fd1.src.tar.xz",
        local_kind="dir",
        required_files=("deu-eng.tei",),
        sqlite_filename="main.sqlite",
        build_mode="freedict_tei_to_sqlite",
        target_lang_code="en",
        name_key="packs.freedict_de_en",
        language_key="languages.german_english",
        source_key="providers.freedict",
        license_name="FreeDict source license; see TEI header",
        license_url="https://freedict.org/license/",
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="freedict-en-de",
        name="FreeDict (EN→DE)",
        language="English → German",
        source="FreeDict",
        size="364 MB",
        url="https://download.freedict.org/dictionaries/eng-deu/1.9-fd1/freedict-eng-deu-1.9-fd1.src.tar.xz",
        wayback_url="https://web.archive.org/web/*/https://download.freedict.org/dictionaries/eng-deu/1.9-fd1/freedict-eng-deu-1.9-fd1.src.tar.xz",
        filename="freedict-eng-deu-1.9-fd1.src.tar.xz",
        local_kind="dir",
        required_files=("eng-deu.tei",),
        sqlite_filename="main.sqlite",
        build_mode="freedict_tei_to_sqlite",
        target_lang_code="de",
        name_key="packs.freedict_en_de",
        language_key="languages.english_german",
        source_key="providers.freedict",
        license_name="FreeDict source license; see TEI header",
        license_url="https://freedict.org/license/",
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="freedict-es-en",
        name="FreeDict (ES→EN)",
        language="Spanish → English",
        source="FreeDict",
        size="121.6 KB",
        url="https://download.freedict.org/dictionaries/spa-eng/0.3.1/freedict-spa-eng-0.3.1.src.tar.xz",
        wayback_url="https://web.archive.org/web/*/https://download.freedict.org/dictionaries/spa-eng/0.3.1/freedict-spa-eng-0.3.1.src.tar.xz",
        filename="freedict-spa-eng-0.3.1.src.tar.xz",
        local_kind="dir",
        required_files=("spa-eng.tei",),
        sqlite_filename="main.sqlite",
        build_mode="freedict_tei_to_sqlite",
        target_lang_code="en",
        source_key="providers.freedict",
        download_size_bytes=121_624,
        license_name="GPL 2.0 or later",
        license_url=GPL_2_URL,
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="freedict-en-es",
        name="FreeDict (EN→ES)",
        language="English → Spanish",
        source="FreeDict",
        size="3.72 MB",
        url="https://download.freedict.org/dictionaries/eng-spa/2025.11.23/freedict-eng-spa-2025.11.23.src.tar.xz",
        wayback_url="https://web.archive.org/web/*/https://download.freedict.org/dictionaries/eng-spa/2025.11.23/freedict-eng-spa-2025.11.23.src.tar.xz",
        filename="freedict-eng-spa-2025.11.23.src.tar.xz",
        local_kind="dir",
        required_files=("eng-spa.tei",),
        sqlite_filename="main.sqlite",
        build_mode="freedict_tei_to_sqlite",
        target_lang_code="es",
        source_key="providers.freedict",
        download_size_bytes=3_715_012,
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="wiktionary-de-en",
        name="Wiktionary (DE→EN)",
        language="German → English",
        source="Kaikki",
        size="2.54 GB",
        url="https://kaikki.org/dictionary/raw-wiktextract-data.jsonl.gz",
        wayback_url="https://web.archive.org/web/*/https://kaikki.org/dictionary/raw-wiktextract-data.jsonl.gz",
        filename="raw-wiktextract-data-de-en.jsonl.gz",
        local_kind="file",
        sqlite_filename="main.sqlite",
        build_mode="kaikki_glosses_to_sqlite",
        source_lang_code="de",
        gloss_language="en",
        download_size_bytes=2_535_682_507,
        license_name="CC BY-SA / GFDL Wiktionary terms",
        license_url="https://kaikki.org/dictionary/rawdata.html",
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="wiktionary-es-en",
        name="Wiktionary (ES→EN)",
        language="Spanish → English",
        source="Kaikki",
        size="2.67 GB",
        url="https://kaikki.org/dictionary/raw-wiktextract-data.jsonl.gz",
        wayback_url="https://web.archive.org/web/*/https://kaikki.org/dictionary/raw-wiktextract-data.jsonl.gz",
        filename="raw-wiktextract-data.jsonl.gz",
        local_kind="file",
        sqlite_filename="main.sqlite",
        build_mode="kaikki_glosses_to_sqlite",
        source_lang_code="es",
        gloss_language="en",
        download_size_bytes=2_665_722_104,
        license_name="CC BY-SA / GFDL Wiktionary terms",
        license_url="https://kaikki.org/dictionary/rawdata.html",
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="wiktionary-en-es",
        name="Wiktionary (EN→ES)",
        language="English → Spanish",
        source="Kaikki",
        size="2.67 GB",
        url="https://kaikki.org/dictionary/raw-wiktextract-data.jsonl.gz",
        wayback_url="https://web.archive.org/web/*/https://kaikki.org/dictionary/raw-wiktextract-data.jsonl.gz",
        filename="raw-wiktextract-data-en-es.jsonl.gz",
        local_kind="file",
        sqlite_filename="main.sqlite",
        build_mode="kaikki_translations_to_sqlite",
        source_lang_code="en",
        target_lang_code="es",
        download_size_bytes=2_665_722_104,
        license_name="CC BY-SA / GFDL Wiktionary terms",
        license_url="https://kaikki.org/dictionary/rawdata.html",
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="cc-cedict-zh-en",
        name="CC-CEDICT",
        language="Chinese → English",
        source="MDBG",
        size="9.7 MB",
        url="https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.zip",
        wayback_url="https://web.archive.org/web/*/https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.zip",
        filename="cedict_1_0_ts_utf-8_mdbg.zip",
        local_kind="dir",
        required_files=("cedict_ts.u8",),
        name_key="packs.cc_cedict",
        language_key="languages.chinese_english",
        source_key="providers.mdbg",
        license_name="CC BY-SA 4.0",
        license_url=CC_BY_SA_4_URL,
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
]

EMBEDDING_PACKS = [
    LanguagePackInfo(
        pack_id="embed-en-cc",
        name="fastText English (Common Crawl)",
        language="English",
        source="fastText",
        size="4.5 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz",
        wayback_url="https://web.archive.org/web/2025/https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz",
        filename="cc.en.300.vec.gz",
        local_kind="file",
        name_key="embeddings.fasttext_en",
        language_key="languages.english",
        source_key="providers.fasttext",
        pair_key="en-en",
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="embed-de-cc",
        name="fastText German (Common Crawl)",
        language="German",
        source="fastText",
        size="4.5 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.de.300.vec.gz",
        wayback_url="https://web.archive.org/web/2025/https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.de.300.vec.gz",
        filename="cc.de.300.vec.gz",
        local_kind="file",
        name_key="embeddings.fasttext_de",
        language_key="languages.german",
        source_key="providers.fasttext",
        pair_key="de-de",
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="embed-ja-cc",
        name="fastText Japanese (Common Crawl)",
        language="Japanese",
        source="fastText",
        size="4.2 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ja.300.vec.gz",
        wayback_url="https://web.archive.org/web/2025/https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ja.300.vec.gz",
        filename="cc.ja.300.vec.gz",
        local_kind="file",
        name_key="embeddings.fasttext_ja",
        language_key="languages.japanese",
        source_key="providers.fasttext",
        pair_key="ja-ja",
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="embed-es-cc",
        name="fastText Spanish (Common Crawl)",
        language="Spanish",
        source="fastText",
        size="1.2 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.vec.gz",
        wayback_url="https://web.archive.org/web/*/https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.vec.gz",
        filename="cc.es.300.vec.gz",
        local_kind="file",
        source_key="providers.fasttext",
        pair_key="es-es",
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
]

CROSS_EMBEDDING_PACKS = [
    LanguagePackInfo(
        pack_id="embed-xling-en",
        name="fastText English (Aligned)",
        language="English (Aligned)",
        source="fastText",
        size="5.69 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.en.align.vec",
        wayback_url="https://web.archive.org/web/2025/https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.en.align.vec",
        filename="wiki.en.align.vec",
        local_kind="file",
        name_key="embeddings.fasttext_en_aligned",
        language_key="languages.english_aligned",
        source_key="providers.fasttext",
        pair_key="en-ja",
        download_size_bytes=5_685_446_378,
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="embed-xling-de",
        name="fastText German (Aligned)",
        language="German (Aligned)",
        source="fastText",
        size="1.4 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.de.align.vec",
        wayback_url="https://web.archive.org/web/2025/https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.de.align.vec",
        filename="wiki.de.align.vec",
        local_kind="file",
        name_key="embeddings.fasttext_de_aligned",
        language_key="languages.german_aligned",
        source_key="providers.fasttext",
        pair_key="de-en",
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="embed-xling-ja",
        name="fastText Japanese (Aligned)",
        language="Japanese (Aligned)",
        source="fastText",
        size="1.2 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.ja.align.vec",
        wayback_url="https://web.archive.org/web/2025/https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.ja.align.vec",
        filename="wiki.ja.align.vec",
        local_kind="file",
        name_key="embeddings.fasttext_ja_aligned",
        language_key="languages.japanese_aligned",
        source_key="providers.fasttext",
        pair_key="en-ja",
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    LanguagePackInfo(
        pack_id="embed-xling-es",
        name="fastText Spanish (Aligned)",
        language="Spanish (Aligned)",
        source="fastText",
        size="2.23 GB",
        url="https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.es.align.vec",
        wayback_url="https://web.archive.org/web/*/https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.es.align.vec",
        filename="wiki.es.align.vec",
        local_kind="file",
        source_key="providers.fasttext",
        pair_key="en-es",
        download_size_bytes=2_227_283_009,
        license_name="CC BY-SA 3.0",
        license_url=CC_BY_SA_3_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
]

FREQUENCY_PACKS = [
    FrequencyPackInfo(
        pack_id="freq-en-coca",
        name="COCA English Frequency (Lemmas)",
        language="English",
        source="COCA",
        size="2 MB",
        url="https://www.wordfrequency.info/samples/lemmas_60k.txt",
        wayback_url="https://web.archive.org/web/20210127204059/https://www.wordfrequency.info/samples/lemmas_60k.txt",
        filename="lemmas_60k.txt",
        sqlite_filename="main.sqlite",
        parse_config=ParseConfig(
            delimiter="\t",
            header_starts_with="rank",
            skip_prefixes=("*", "-----"),
        ),
        index_column="lemma",
        name_key="packs.freq_en_coca",
        language_key="languages.english",
        source_key="providers.coca",
        license_name="WordFrequency.info manual/local-use terms",
        license_url="https://www.wordfrequency.info/",
        license_status="manual-review-required",
        distribution_mode=MANUAL_SUPPLY_MODE,
    ),
    FrequencyPackInfo(
        pack_id="freq-en-leipzig-default",
        name="English News Frequency (Lemmas)",
        language="English",
        source="Leipzig Wortschatz",
        size="~280 MB",
        url="https://downloads.wortschatz-leipzig.de/corpora/eng_news_2025_1M.tar.gz",
        wayback_url="https://web.archive.org/web/*/https://downloads.wortschatz-leipzig.de/corpora/eng_news_2025_1M.tar.gz",
        filename="eng_news_2025_1M.tar.gz",
        sqlite_filename="main.sqlite",
        build_mode="en_frequency_pipeline",
        name_key="packs.freq_en_leipzig_default",
        language_key="languages.english",
        source_key="providers.leipzig",
        download_size_bytes=291_283_406,
        license_name="Leipzig downloadable corpus CC BY",
        license_url="https://wortschatz.informatik.uni-leipzig.de/en/download/eng",
        license_status=EXPECTED_NOT_VERIFIED,
        distribution_mode=AUTO_DOWNLOAD_MODE,
        license_notes=(
            "Auto-download/build is intended for user-local source acquisition.",
            "Bundled or hosted converted artifacts remain review-required.",
        ),
    ),
    FrequencyPackInfo(
        pack_id="freq-ja-bccwj",
        name="BCCWJ Japanese Frequency (SUW)",
        language="Japanese",
        source="NINJAL",
        size="50 MB",
        url="https://repository.ninjal.ac.jp/record/3234/files/BCCWJ_frequencylist_suw_ver1_0.zip",
        wayback_url="https://web.archive.org/web/0/https://repository.ninjal.ac.jp/record/3234/files/BCCWJ_frequencylist_suw_ver1_0.zip",
        filename="BCCWJ_frequencylist_suw_ver1_0.zip",
        sqlite_filename="main.sqlite",
        source_filename="BCCWJ_frequencylist_suw_ver1_0.tsv",
        parse_config=ParseConfig(
            delimiter="\t",
            header_starts_with="rank",
            skip_prefixes=(),
        ),
        index_column="lemma",
        name_key="packs.freq_ja_bccwj",
        language_key="languages.japanese",
        source_key="providers.ninjal",
        license_name="NINJAL BCCWJ terms",
        license_url="https://clrd.ninjal.ac.jp/bccwj/en/freq-list.html#freq-list",
        license_status="manual-review-required",
        distribution_mode=MANUAL_SUPPLY_MODE,
        license_notes=(
            "Quality-preferred en-ja target-frequency source.",
            "Public upstream page frames usage as research or educational.",
            "Do not bundle or host converted artifacts without policy review.",
        ),
    ),
    FrequencyPackInfo(
        pack_id="freq-de-default",
        name="German News Frequency (Lemmas)",
        language="German",
        source="Leipzig + LanguageTool",
        size="~80 MB",
        url="https://downloads.wortschatz-leipzig.de/corpora/deu_news_2023_1M.tar.gz",
        wayback_url="https://web.archive.org/web/*/https://downloads.wortschatz-leipzig.de/corpora/deu_news_2023_1M.tar.gz",
        filename="deu_news_2023_1M.tar.gz",
        sqlite_filename="main.sqlite",
        build_mode="de_frequency_pipeline",
        name_key="packs.freq_de_default",
        language_key="languages.german",
        source_key="providers.leipzig_languagetool",
        license_name="Composite local build: Leipzig + LanguageTool + optional open inputs",
        license_url="https://wortschatz.uni-leipzig.de/en/download/",
        license_status="source-stack-audited",
        distribution_mode=AUTO_DOWNLOAD_MODE,
        license_notes=(
            "Auto-download/build is intended for user-local source acquisition.",
            "Bundled or hosted composite artifacts remain review-required.",
        ),
    ),
    FrequencyPackInfo(
        pack_id="freq-es-spalex-v1",
        name="SPALEX Spanish Frequency (Words)",
        language="Spanish",
        source="SPALEX",
        size="5.2 MB",
        url="https://ndownloader.figshare.com/files/11826623",
        wayback_url="https://web.archive.org/web/*/https://ndownloader.figshare.com/files/11826623",
        filename="word_info.csv",
        sqlite_filename="main.sqlite",
        source_filename="word_info.csv",
        source_version="10.6084/m9.figshare.5924794.v4",
        build_mode="spalex_frequency_pipeline",
        name_key="packs.freq_es_spalex",
        language_key="languages.spanish",
        source_key="providers.spalex",
        download_size_bytes=5_407_807,
        license_name="CC BY 4.0",
        license_url=CC_BY_4_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
    FrequencyPackInfo(
        pack_id="freq-es-cde",
        name="Corpus del Espanol Frequency (sample)",
        language="Spanish",
        source="Corpus del Espanol",
        size="42.9 KB",
        url="https://www.wordfrequency.info/files/spanish/spanish_lemmas20k.txt",
        wayback_url="https://web.archive.org/web/*/https://www.wordfrequency.info/files/spanish/spanish_lemmas20k.txt",
        filename="spanish_lemmas20k.txt",
        sqlite_filename="main.sqlite",
        parse_config=ParseConfig(
            delimiter="\t",
            header_starts_with="ID",
            skip_prefixes=("----",),
            encoding="latin-1",
        ),
        index_column="lemma",
        download_size_bytes=42_922,
        license_name="WordFrequency.info manual/local-use terms",
        license_url="https://www.wordfrequency.info/spanish/",
        license_status="manual-review-required",
        distribution_mode=MANUAL_SUPPLY_MODE,
    ),
]


POS_OVERLAY_PACKS = [
    PosOverlayPackInfo(
        pack_id=DEFAULT_UD_ANCORA_PACK_ID,
        name="UD AnCora Spanish POS Overlay",
        language="Spanish",
        source=DEFAULT_UD_ANCORA_SOURCE_NAME,
        size="~20 MB",
        url=DEFAULT_UD_ANCORA_SOURCE_URL,
        wayback_url=(
            "https://web.archive.org/web/*/"
            "https://universaldependencies.org/treebanks/es_ancora/index.html"
        ),
        filename="ud-spanish-ancora-sources",
        sqlite_filename="main.sqlite",
        source_urls=tuple(DEFAULT_UD_ANCORA_URLS),
        provider=DEFAULT_UD_ANCORA_PROVIDER,
        name_key="packs.pos_es_ud_ancora",
        language_key="languages.spanish",
        source_key="providers.universal_dependencies",
        license_name="CC BY 4.0",
        license_url=CC_BY_4_URL,
        license_status=VERIFIED_FROM_UPSTREAM,
        distribution_mode=AUTO_DOWNLOAD_MODE,
    ),
]


SEMANTIC_PACKS = [
    SemanticPackInfo(
        pack_id="en-es-active-only-combined-full-v1-tranche-011",
        name="English-Spanish sentence veto semantic reference",
        pair="en-es",
        source="LexiShift semantic pack builder",
        size="local reference",
        name_key="packs.semantic_en_es_sentence_veto",
        source_key="providers.lexishift_semantic_pack_builder",
        license_name="Derived local artifact; source notices apply",
        license_status="local-reference",
        distribution_mode="local-copy",
        license_notes=(
            "Generated semantic reference inventory used for local sentence-veto publication.",
            "Installing this pack copies a local reference inventory into the app data root; it is not a hosted converted-artifact redistribution approval.",
            "Underlying source data notices remain listed with the frequency, dictionary, and POS packs used to build or validate the reference.",
        ),
    ),
]
