BUILTIN_THEMES = {
    "light_sand": {
        "bg": "#F6F2EB",
        "panel_top": "#FBF8F3",
        "panel_bottom": "#EFE7DC",
        "panel_border": "#D8CDBD",
        "text": "#1F1F1F",
        "muted": "#5C5C5C",
        "accent": "#9A6A2B",
        "accent_soft": "#E9D6BF",
        "primary": "#2F2F2F",
        "primary_hover": "#232323",
        "table_bg": "#FFFFFF",
        "table_sel_bg": "#E7D9C6",
    },
    "chalk": {
        "bg": "#F2F2EE",
        "panel_top": "#F7F7F2",
        "panel_bottom": "#E5E2DB",
        "panel_border": "#CBC4BA",
        "text": "#1B1A18",
        "muted": "#5A5752",
        "accent": "#4B6B5D",
        "accent_soft": "#D9E3DE",
        "primary": "#3A3A3A",
        "primary_hover": "#2E2E2E",
        "table_bg": "#FFFFFF",
        "table_sel_bg": "#DDE7E0",
    },
    "dusk": {
        "bg": "#1F1E1C",
        "panel_top": "#2A2724",
        "panel_bottom": "#1D1B19",
        "panel_border": "#3B352F",
        "text": "#E9E2DA",
        "muted": "#B0A79D",
        "accent": "#D1A56F",
        "accent_soft": "#3B2F23",
        "primary": "#4A443E",
        "primary_hover": "#5A534C",
        "table_bg": "#24211E",
        "table_sel_bg": "#3F352D",
    },
    "night_slate": {
        "bg": "#151A1F",
        "panel_top": "#1E242B",
        "panel_bottom": "#12171C",
        "panel_border": "#2B333C",
        "text": "#E3E8EE",
        "muted": "#9AA5B1",
        "accent": "#7CA6C8",
        "accent_soft": "#1F2C36",
        "primary": "#2B3947",
        "primary_hover": "#344454",
        "table_bg": "#171C22",
        "table_sel_bg": "#233040",
    },
}
