(() => {
  const root = (globalThis.LexiShift = globalThis.LexiShift || {});
  root.defaults = {
    enabled: true,
    rules: [],
    highlightEnabled: true,
    highlightColor: "#9AA0A6",
    maxOnePerTextBlock: false,
    allowAdjacentReplacements: true,
    maxReplacementsPerPage: 0,
    maxReplacementsPerLemmaPerPage: 0,
    debugEnabled: false,
    debugFocusWord: "",
    uiLanguage: "system",
    rulesSource: "editor",
    rulesFileName: "",
    rulesUpdatedAt: "",
    sourceLanguage: "en",
    targetLanguage: "en",
    srsPairAuto: true,
    srsSelectedProfileId: "default",
    srsProfileId: "default",
    srsProfiles: {},
    srsEnabled: false,
    srsPair: "en-en",
    srsMaxActive: 40,
    srsBootstrapTopN: 800,
    srsInitialActiveCount: 40,
    srsSoundEnabled: true,
    srsHighlightColor: "#2F74D0",
    srsFeedbackSrsEnabled: true,
    srsFeedbackRulesEnabled: false,
    srsExposureLoggingEnabled: true,
    profileBackgroundEnabled: false,
    profileBackgroundAssetId: "",
    profileBackgroundOpacity: 0.18,
    profileBackgroundBackdropColor: "#fbf7f0",
    srsRulesetUpdatedAt: ""
  };
})();
