(() => {
  const root = (globalThis.LexiShift = globalThis.LexiShift || {});

  function buildElements(domArg) {
    const dom = domArg && typeof domArg === "object" ? domArg : {};
    return {
      profileBackground: {
        profileBgBackdropColorInput: dom.profileBgBackdropColorInput,
        profileBgEnabledInput: dom.profileBgEnabledInput,
        profileBgOpacityInput: dom.profileBgOpacityInput,
        profileBgOpacityValueOutput: dom.profileBgOpacityValueOutput,
        profileBgFileInput: dom.profileBgFileInput,
        profileBgRemoveButton: dom.profileBgRemoveButton,
        profileBgApplyButton: dom.profileBgApplyButton,
        profileBgStatusOutput: dom.profileBgStatusOutput,
        profileBgPreviewWrap: dom.profileBgPreviewWrap,
        profileBgPreviewImage: dom.profileBgPreviewImage,
        profileBgFocalMarker: dom.profileBgFocalMarker,
        profileBgPositionResetButton: dom.profileBgPositionResetButton,
        profileCardThemeHueInput: dom.profileCardThemeHueInput,
        profileCardThemeHueValueOutput: dom.profileCardThemeHueValueOutput,
        profileCardThemeSaturationInput: dom.profileCardThemeSaturationInput,
        profileCardThemeSaturationValueOutput: dom.profileCardThemeSaturationValueOutput,
        profileCardThemeBrightnessInput: dom.profileCardThemeBrightnessInput,
        profileCardThemeBrightnessValueOutput: dom.profileCardThemeBrightnessValueOutput,
        profileCardThemeTransparencyInput: dom.profileCardThemeTransparencyInput,
        profileCardThemeTransparencyValueOutput: dom.profileCardThemeTransparencyValueOutput,
        profileCardThemeResetButton: dom.profileCardThemeResetButton
      },
      profileRulesets: {
        profileRulesetsList: dom.profileRulesetsList,
        profileRulesetsStatus: dom.profileRulesetsStatus,
        profileRulesetsRefreshButton: dom.profileRulesetsRefreshButton
      },
      srsActions: {
        output: dom.srsRulegenOutput,
        admissionPreviewOutput: dom.srsAdmissionPreviewOutput,
        sampledOutput: dom.srsRulegenSampledOutput,
        admissionPreviewButton: dom.srsAdmissionPreviewButton,
        initializeButton: dom.srsInitializeSetButton,
        rebalancePreviewButton: dom.srsRebalancePreviewButton,
        rebalanceApplyButton: dom.srsRebalanceApplyButton,
        refreshButton: dom.srsRefreshSetButton,
        diagnosticsButton: dom.srsRuntimeDiagnosticsButton,
        sampledButton: dom.srsRulegenSampledButton,
        resetButton: dom.srsResetButton
      },
      rulesShare: {
        rulesInput: dom.rulesInput,
        rulesFileInput: dom.rulesFileInput,
        fileStatus: dom.fileStatus,
        shareCodeInput: dom.shareCodeInput,
        shareCodeScopeInput: dom.shareCodeScopeInput,
        shareCodeCjk: dom.shareCodeCjk
      },
      shareCenter: {
        openExportButton: dom.shareCenterOpenExportButton,
        openImportButton: dom.shareCenterOpenImportButton,
        exportBackdrop: dom.shareCenterExportBackdrop,
        exportModal: dom.shareCenterExportModal,
        exportCloseButton: dom.shareCenterExportCloseButton,
        exportModeFullInput: dom.shareCenterExportModeFullInput,
        exportModeCustomInput: dom.shareCenterExportModeCustomInput,
        treePanel: dom.shareCenterTreePanel,
        importBackdrop: dom.shareCenterImportBackdrop,
        importModal: dom.shareCenterImportModal,
        importCloseButton: dom.shareCenterImportCloseButton,
        parentProfileInput: dom.shareCenterParentProfileInput,
        parentRulesetsInput: dom.shareCenterParentRulesetsInput,
        parentSrsInput: dom.shareCenterParentSrsInput,
        parentAppearanceInput: dom.shareCenterParentAppearanceInput,
        parentModuleHistoriesInput: dom.shareCenterParentModuleHistoriesInput,
        targetInputs: dom.shareCenterTargetInputs,
        targetProfileSettingsInput: dom.shareCenterTargetProfileSettingsInput,
        srsPairItemsRoot: dom.shareCenterSrsPairItemsRoot,
        srsPairStatus: dom.shareCenterSrsPairStatus,
        targetAppearanceThemeInput: dom.shareCenterTargetAppearanceThemeInput,
        rulesetItemsRoot: dom.shareCenterRulesetItemsRoot,
        rulesetStatus: dom.shareCenterRulesetStatus,
        moduleItemsRoot: dom.shareCenterModuleItemsRoot,
        moduleStatus: dom.shareCenterModuleStatus,
        summaryTarget: dom.shareCenterSummaryTarget,
        summaryGroups: dom.shareCenterSummaryGroups,
        summaryOutput: dom.shareCenterSummaryOutput,
        generateButton: dom.shareCenterGenerateButton,
        importButton: dom.shareCenterImportButton,
        importFileInput: dom.shareCenterImportFileInput,
        importFileNameOutput: dom.shareCenterImportFileNameOutput,
        importStatusOutput: dom.shareCenterImportStatus,
        exportStatusOutput: dom.shareCenterExportStatus,
        statusOutput: dom.shareCenterStatus
      },
      helperActions: {
        debugHelperTestButton: dom.debugHelperTestButton,
        debugHelperTestOutput: dom.debugHelperTestOutput,
        debugOpenDataDirButton: dom.debugOpenDataDirButton,
        debugOpenDataDirOutput: dom.debugOpenDataDirOutput
      },
      srsProfileRuntime: {
        sourceLanguageInput: dom.sourceLanguageInput,
        targetLanguageInput: dom.targetLanguageInput,
        srsEnabledInput: dom.srsEnabledInput,
        srsMaxActiveInput: dom.srsMaxActiveInput,
        srsBootstrapTopNInput: dom.srsBootstrapTopNInput,
        srsInitialActiveCountInput: dom.srsInitialActiveCountInput,
        srsTopicInterestsInput: dom.srsTopicInterestsInput,
        srsProficiencyEstimateInput: dom.srsProficiencyEstimateInput,
        srsChallengeTargetInput: dom.srsChallengeTargetInput,
        srsSoundInput: dom.srsSoundInput,
        srsHighlightInput: dom.srsHighlightInput,
        srsHighlightTextInput: dom.srsHighlightTextInput,
        srsFeedbackSrsInput: dom.srsFeedbackSrsInput,
        srsFeedbackRulesInput: dom.srsFeedbackRulesInput,
        srsExposureLoggingInput: dom.srsExposureLoggingInput,
        srsProfileIdInput: dom.srsProfileIdInput,
        srsProfileRefreshButton: dom.srsProfileRefreshButton
      },
      displayReplacement: {
        highlightEnabledInput: dom.highlightEnabledInput,
        highlightColorInput: dom.highlightColorInput,
        debugEnabledInput: dom.debugEnabledInput,
        debugFocusInput: dom.debugFocusInput,
        maxOnePerBlockInput: dom.maxOnePerBlockInput,
        allowAdjacentInput: dom.allowAdjacentInput,
        maxReplacementsPerPageInput: dom.maxReplacementsPerPageInput,
        maxReplacementsPerLemmaPageInput: dom.maxReplacementsPerLemmaPageInput
      },
      pageInit: {
        enabledInput: dom.enabledInput,
        highlightEnabledInput: dom.highlightEnabledInput,
        highlightColorInput: dom.highlightColorInput,
        highlightColorText: dom.highlightColorText,
        maxOnePerBlockInput: dom.maxOnePerBlockInput,
        allowAdjacentInput: dom.allowAdjacentInput,
        maxReplacementsPerPageInput: dom.maxReplacementsPerPageInput,
        maxReplacementsPerLemmaPageInput: dom.maxReplacementsPerLemmaPageInput,
        debugEnabledInput: dom.debugEnabledInput,
        debugFocusInput: dom.debugFocusInput,
        srsAdmissionPreviewOutput: dom.srsAdmissionPreviewOutput,
        srsRulegenSampledOutput: dom.srsRulegenSampledOutput,
        srsRulegenOutput: dom.srsRulegenOutput,
        debugHelperTestOutput: dom.debugHelperTestOutput,
        debugOpenDataDirOutput: dom.debugOpenDataDirOutput,
        languageSelect: dom.languageSelect,
        rulesInput: dom.rulesInput,
        fileStatus: dom.fileStatus,
        customRulesetEnabledInput: dom.customRulesetEnabledInput
      },
      eventWiring: {
        saveButton: dom.saveButton,
        importFileButton: dom.importFileButton,
        exportFileButton: dom.exportFileButton,
        rulesSourceInputs: dom.rulesSourceInputs,
        customRulesetEnabledInput: dom.customRulesetEnabledInput,
        highlightEnabledInput: dom.highlightEnabledInput,
        highlightColorInput: dom.highlightColorInput,
        highlightColorText: dom.highlightColorText,
        maxOnePerBlockInput: dom.maxOnePerBlockInput,
        allowAdjacentInput: dom.allowAdjacentInput,
        maxReplacementsPerPageInput: dom.maxReplacementsPerPageInput,
        maxReplacementsPerLemmaPageInput: dom.maxReplacementsPerLemmaPageInput,
        srsEnabledInput: dom.srsEnabledInput,
        srsProfileIdInput: dom.srsProfileIdInput,
        srsProfileRefreshButton: dom.srsProfileRefreshButton,
        profileBgEnabledInput: dom.profileBgEnabledInput,
        profileBgBackdropColorInput: dom.profileBgBackdropColorInput,
        profileBgOpacityInput: dom.profileBgOpacityInput,
        profileBgFileInput: dom.profileBgFileInput,
        profileBgRemoveButton: dom.profileBgRemoveButton,
        profileBgApplyButton: dom.profileBgApplyButton,
        profileBgPositionResetButton: dom.profileBgPositionResetButton,
        profileCardThemeHueInput: dom.profileCardThemeHueInput,
        profileCardThemeSaturationInput: dom.profileCardThemeSaturationInput,
        profileCardThemeBrightnessInput: dom.profileCardThemeBrightnessInput,
        profileCardThemeTransparencyInput: dom.profileCardThemeTransparencyInput,
        profileCardThemeResetButton: dom.profileCardThemeResetButton,
        srsMaxActiveInput: dom.srsMaxActiveInput,
        srsBootstrapTopNInput: dom.srsBootstrapTopNInput,
        srsInitialActiveCountInput: dom.srsInitialActiveCountInput,
        srsTopicInterestsInput: dom.srsTopicInterestsInput,
        srsProficiencyEstimateInput: dom.srsProficiencyEstimateInput,
        srsChallengeTargetInput: dom.srsChallengeTargetInput,
        srsSoundInput: dom.srsSoundInput,
        srsHighlightInput: dom.srsHighlightInput,
        srsHighlightTextInput: dom.srsHighlightTextInput,
        srsFeedbackSrsInput: dom.srsFeedbackSrsInput,
        srsFeedbackRulesInput: dom.srsFeedbackRulesInput,
        srsExposureLoggingInput: dom.srsExposureLoggingInput,
        srsInitializeSetButton: dom.srsInitializeSetButton,
        srsRebalancePreviewButton: dom.srsRebalancePreviewButton,
        srsRebalanceApplyButton: dom.srsRebalanceApplyButton,
        srsRefreshSetButton: dom.srsRefreshSetButton,
        srsRuntimeDiagnosticsButton: dom.srsRuntimeDiagnosticsButton,
        srsAdmissionPreviewButton: dom.srsAdmissionPreviewButton,
        srsRulegenSampledButton: dom.srsRulegenSampledButton,
        srsResetButton: dom.srsResetButton,
        srsAdmissionPreviewOutput: dom.srsAdmissionPreviewOutput,
        srsRulegenSampledOutput: dom.srsRulegenSampledOutput,
        debugHelperTestButton: dom.debugHelperTestButton,
        debugOpenDataDirButton: dom.debugOpenDataDirButton,
        debugEnabledInput: dom.debugEnabledInput,
        debugFocusInput: dom.debugFocusInput,
        enabledInput: dom.enabledInput,
        languageSelect: dom.languageSelect,
        sourceLanguageInput: dom.sourceLanguageInput,
        targetLanguageInput: dom.targetLanguageInput,
        targetLanguageGearButton: dom.targetLanguageGearButton,
        targetLanguageModulesList: dom.targetLanguageModulesList,
        targetLanguagePrefsModalBackdrop: dom.targetLanguagePrefsModalBackdrop,
        targetLanguagePrefsModalOkButton: dom.targetLanguagePrefsModalOkButton,
        openDesktopAppButton: dom.openDesktopAppButton,
        openBdPluginButton: dom.openBdPluginButton,
        generateCodeButton: dom.generateCodeButton,
        importCodeButton: dom.importCodeButton,
        copyCodeButton: dom.copyCodeButton,
        srsRulegenOutput: dom.srsRulegenOutput
      }
    };
  }

  root.optionsControllerGraphElements = {
    buildElements
  };
})();
