(() => {
  const root = (globalThis.LexiShift = globalThis.LexiShift || {});

  function createDomAliases(dom) {
    const source = dom && typeof dom === "object" ? dom : {};
    return {
      optionsMainContent: source.optionsMainContent || null,
      enabledInput: source.enabled || null,
      highlightEnabledInput: source.highlightEnabled || null,
      highlightColorInput: source.highlightColor || null,
      highlightColorText: source.highlightColorText || null,
      maxOnePerBlockInput: source.maxOnePerBlock || null,
      allowAdjacentInput: source.allowAdjacent || null,
      maxReplacementsPerPageInput: source.maxReplacementsPerPage || null,
      maxReplacementsPerLemmaPageInput: source.maxReplacementsPerLemmaPage || null,
      debugEnabledInput: source.debugEnabled || null,
      debugFocusInput: source.debugFocusWord || null,
      srsEnabledInput: source.srsEnabled || null,
      sourceLanguageInput: source.sourceLanguage || null,
      targetLanguageInput: source.targetLanguage || null,
      targetLanguageGearButton: source.targetLanguageGear || null,
      targetLanguagePrefsModalBackdrop: source.targetLanguagePrefsModalBackdrop || null,
      targetLanguagePrefsModal: source.targetLanguagePrefsModal || null,
      targetLanguagePrefsModalOkButton: source.targetLanguagePrefsModalOk || null,
      targetLanguageModulesList: source.targetLanguageModulesList || null,
      srsProfileIdInput: source.srsProfileId || null,
      srsProfileRefreshButton: source.srsProfileRefresh || null,
      srsProfileStatusOutput: source.srsProfileStatus || null,
      profileBgBackdropColorInput: source.profileBgBackdropColor || null,
      profileBgEnabledInput: source.profileBgEnabled || null,
      profileBgOpacityInput: source.profileBgOpacity || null,
      profileBgOpacityValueOutput: source.profileBgOpacityValue || null,
      profileBgFileInput: source.profileBgFile || null,
      profileBgRemoveButton: source.profileBgRemove || null,
      profileBgApplyButton: source.profileBgApply || null,
      profileBgStatusOutput: source.profileBgStatus || null,
      profileBgPreviewWrap: source.profileBgPreviewWrap || null,
      profileBgPreviewImage: source.profileBgPreview || null,
      profileBgFocalMarker: source.profileBgFocalMarker || null,
      profileBgPositionResetButton: source.profileBgPositionReset || null,
      profileCardThemeHueInput: source.profileCardThemeHue || null,
      profileCardThemeHueValueOutput: source.profileCardThemeHueValue || null,
      profileCardThemeSaturationInput: source.profileCardThemeSaturation || null,
      profileCardThemeSaturationValueOutput: source.profileCardThemeSaturationValue || null,
      profileCardThemeBrightnessInput: source.profileCardThemeBrightness || null,
      profileCardThemeBrightnessValueOutput: source.profileCardThemeBrightnessValue || null,
      profileCardThemeTransparencyInput: source.profileCardThemeTransparency || null,
      profileCardThemeTransparencyValueOutput: source.profileCardThemeTransparencyValue || null,
      profileCardThemeResetButton: source.profileCardThemeReset || null,
      srsMaxActiveInput: source.srsMaxActive || null,
      srsBootstrapTopNInput: source.srsBootstrapTopN || null,
      srsInitialActiveCountInput: source.srsInitialActiveCount || null,
      srsSoundInput: source.srsSoundEnabled || null,
      srsHighlightInput: source.srsHighlightColor || null,
      srsHighlightTextInput: source.srsHighlightColorText || null,
      srsFeedbackSrsInput: source.srsFeedbackSrsEnabled || null,
      srsFeedbackRulesInput: source.srsFeedbackRulesEnabled || null,
      srsExposureLoggingInput: source.srsExposureLoggingEnabled || null,
      srsInitializeSetButton: source.srsInitializeSet || null,
      srsRefreshSetButton: source.srsRefreshSet || null,
      srsRuntimeDiagnosticsButton: source.srsRuntimeDiagnostics || null,
      srsRulegenSampledButton: source.srsRulegenSampledPreview || null,
      srsRulegenOutput: source.srsRulegenOutput || null,
      srsResetButton: source.srsReset || null,
      debugHelperTestButton: source.debugHelperTest || null,
      debugHelperTestOutput: source.debugHelperTestOutput || null,
      debugOpenDataDirButton: source.debugOpenDataDir || null,
      debugOpenDataDirOutput: source.debugOpenDataDirOutput || null,
      languageSelect: source.uiLanguage || null,
      rulesInput: source.rules || null,
      saveButton: source.save || null,
      rulesSourceInputs: source.rulesSourceInputs || null,
      rulesFileInput: source.rulesFile || null,
      importFileButton: source.importFile || null,
      exportFileButton: source.exportFile || null,
      fileStatus: source.fileStatus || null,
      shareCodeInput: source.shareCode || null,
      shareCodeScopeInput: source.shareCodeScope || null,
      shareCodeCjk: source.shareCodeCjk || null,
      generateCodeButton: source.generateCode || null,
      importCodeButton: source.importCode || null,
      copyCodeButton: source.copyCode || null,
      openDesktopAppButton: source.openDesktopApp || null,
      openBdPluginButton: source.openBdPlugin || null
    };
  }

  root.optionsDomAliases = {
    createDomAliases
  };
})();
